id: A7446F3FF
title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress of the
  Jarung Kashor Stūpa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:47:43.851864
  last_modified_at: 2022-03-01 04:47:43.851871
