id: A7446F3FF
title: Prayer to the Three Great Stūpas of Kathmandu
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:47:43.863330
  last_modified_at: 2022-03-01 04:47:43.863333
