id: A7446F3FF
title: In Praise of Yangleshö in Nepal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:47:43.859957
  last_modified_at: 2022-03-01 04:47:43.859960
