id: A7446F3FF
title: A Prayer to the Stūpa of Jarung Khashor in Boudha
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:47:43.854342
  last_modified_at: 2022-03-01 04:47:43.854380
