id: A7446F3FF
title: A Prayer to the Three Stūpas of Nepal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:47:43.858461
  last_modified_at: 2022-03-01 04:47:43.858464
