id: A7446F3FF
title: Upon Arriving at Yangleshö
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:47:43.865022
  last_modified_at: 2022-03-01 04:47:43.865025
